#!/bin/bash 

list="" 

for m in {605..610} {615..618}  
do 
	google-chrome  --headless --disable-gpu --print-to-pdf=d$m.pdf "https://azharegypt.org/emis/cms/reposid/lcms4/cntp03prn.php?lid=$m&cid=107"
list+=" d$m.pdf"
#echo $list 
done

pdfunite $list nodom.pdf 

