#!/bin/bash 

list="" 

for m in {644..646} 649 647 648 650 651 657 658 659  
do 
	google-chrome  --headless --disable-gpu --print-to-pdf=d$m.pdf "https://azharegypt.org/emis/cms/reposid/lcms4/cntp03prn.php?lid=$m&cid=107"
list+=" d$m.pdf"
#echo $list 
done

pdfunite $list osol.pdf 

