#!/bin/bash 

output=tarikh.pdf 
list="" 

for m in 638 {640..642} {652..656} {660..664}
do 
	google-chrome  --headless --disable-gpu --print-to-pdf=d$m.pdf "https://azharegypt.org/emis/cms/reposid/lcms4/cntp03prn.php?lid=$m&cid=107"
list+=" d$m.pdf"
#echo $list 
done

pdfunite $list $output 
xdg-open $output 
